### ISSUE TITLE
Unfortunately, the selected content type 'H5P.AdvancedText 1.1' isn't installed on this system.

### ISSUE THREAD

**Issue by dezglidden** [h5p/h5p-advanced-text#14]
Hi,

I'm debugging an issue with H5p where various content types rely on Advanced Text. Although Moodle is showing that it's installed I receive "Unfortunately, the selected content type 'H5P.AdvancedText 1.1' isn't installed on this system." when attempting to upload a demo content file. I don't believe it's a bug with this library but I was wondering if you had a demo .h5p file that I could use for testing purposes, under the belief that if I upload it to an activity it should install or update the library.

Thanks

Dez

**Comment by otacke** [comment]
@dezglidden Have you tried https://h5p.org/advanced-fill-the-blanks ?

**Comment by otacke** [comment]
@dezglidden AdvancedText is not a content type, but only a library, so you'd have to upload a content that includes it and you'd have to temporarily use

`define('H5P_DEV', true);`

in moodle's config to allow installing libraries with the same version number.

Alternatively, you could clone this repository and then use the [H5P cli tool](https://h5p.org/h5p-cli-guide) to pack it to an H5P file that you can upload on the library settings page.

**Comment by dezglidden** [comment]
Thanks otacke,

Yeah I've already uploaded the advanced-fill-the-blanks and still get the error message. Thanks for the cli pointer, I'll explore this just now.

Cheers

**Comment by otacke** [comment]
@dezglidden My bad, _Advanced Fill in the Blanks_ doesn't use AdvancedText, it seems. Not sure what content type does.
